name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DROPLET_HOSTIP }}
          username: ${{ secrets.DROPLET_USER1 }}
          key:  ${{ secrets.DROPLET_PEKEY }}
          port: 22
          script: |
            sudo rm -rf oysloeadmin
            git clone https://github.com/danielagblo/oysloeadmin.git
            cd oysloeadmin
            echo "VITE_API_BASE=https://staging-api.oysloe.com/api-v1" > .env
            sudo rm -rf dist/* 
            git pull origin main           
            npm install                   
            npm run build                 
            
            sudo rm -rf /var/www/oysloeadmin/dist/*

            sudo cp -r dist/* /var/www/oysloeadmin/dist

            sudo chown -R www-data:www-data /var/www/oysloeadmin
            sudo chmod -R 755 /var/www/oysloeadmin

            sudo systemctl restart nginx
